# Generated by Django 3.2.19 on 2023-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
